---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cnpg-system
  namespace: flux-system
spec:
  interval: 12h
  url: https://cloudnative-pg.github.io/charts

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cnpg-system
  namespace: flux-system
spec:
  interval: 10m
  path: "./infra/cnpg-system"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
