apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  namespace: monitoring
stringData:
  admin-user: ENC[AES256_GCM,data:X8to6q8=,iv:qJ1KYzBmfIgKY8cLTUcTMiXhClRmr/EAg7X1MUCcXHA=,tag:eZwNkN+htrWjaacPYaN7wQ==,type:str]
  admin-password: ENC[AES256_GCM,data:vMyrQ20IBTqFzg==,iv:p6uatSjcj/FYb0PhsvPJR54DLy29UIlWC3ZNRG7kFC4=,tag:nCpSUmDIqPv9tNWg32eckg==,type:str]
sops:
  age:
    - recipient: age1vtnndcu4fmcthtam7zqlpt2nuqms7vhfdmljs08zzxkrnjy7344qt0td4v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhRmxNZVMyOWc5M0ZMZ2ow
        d1ZaMDVwNDRYbWJTa0lyQzkvZGg4SzQxbWlrClJuN3ZUcHlPZlNnNitTa1RuUVBi
        TWZkbVFCYnVoTGxnRUFxK3B3VkFyMzgKLS0tIDVkUlliUFVaYWp5VnpFZ3dzcDRx
        ZFROV0NKdHhheFcvWThOK1NCaWpCTjQKbdd+VVpamLDyPUqNv+CQ2aEU+4wq9XRY
        zVL8HuK3HntizznR30LYhoGC9dNjifsv1+59Cdbo9wD5kiYc14wWvA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-11T05:50:07Z"
  mac: ENC[AES256_GCM,data:SO+LYp0yO3rjAeCHQrsjIaQVem3aOKPaZF5XwDG1N3SVgr4JxiWRvu1PY7SD2LjS2SFAr+BWcNKtO8mb99U4pDXxZyN+SytP40rCPRfFiNBdgDCpyiySNXH4heLk5jhw7UitAi7BOo40+A/LbQifYsbSsCe/kAFddEPdy0dzJvw=,iv:HB/dG93v15JxRW45a270Xm6h3x+U5MM3muQ2pPpUqHc=,tag:44rENLd1lqtYi3WFMKZFMw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: sing-box-tun-config
  namespace: monitoring
type: Opaque
stringData:
  config.json: ENC[AES256_GCM,data:gruwoNQp52ygY/DfJ1cnO07PwMmt7Ql7VsoUFaN0B47sitIiGiS512GMkonITCzXR6oZEtvGU9MyxnO3UeFFWO1DePzYJCZze+IowHylDeHTl6AmjJP9MZUg911QArvMyzEoOniUThUWFQQ0QjPSB4s8MklrUOM5FLE066E5H29H5G7vsCcyan0mLlhA5xyfpE9z1H8abAkYPZENwLQ8i1F8TSJ72hChYTcrpQD4veDv+we7R4VjPypLnePMW8qHe2nxbHT2gKJgQe+/Ilxo2uLbDljs8BNoVEMJxPfAukMCUhxyInMZfePCtEvEjvShisR0YihsHN+VUZSS2QiANzx6sR13l9rPXhffiDrvwR8I/+70Y5RPBiaqlHY1ucZ2nklxlP2lUX1g+68eSA12X/dDmDEg8VcmQ5hM5smGRbYKz3NysxEKb0haKtNlbgnUfP7IVw7bateMtq8vM8v3mGPJ1ZADs1rgBw2gXUC6s1g4dpTpp2YsoR0n5dJVI917kHO3evJU7/p23ykIehzMSFeBEbm13TXB0Sl/0YbMduuFQ8aiVNBXMv3qRxtbSW6ylxVEhLs7ZrKhXjMFc8sZy0l5kHGac0G+gxPqwCRDSOpreSR5YTqoZ8lhMeV1wDoQzpU3YUamZpw9qWcIIEzSBxDY0djL3MDh3g8CkUVRQpY/lBWAChP884OSIAXAyDGxcNUFgOSQR36sjFW7WeDgzw9mWY9i5UFHH1IXIqOeWBryLTVSIZ0+578vRn/k0Rpn9NvTKlqHAgPwePPqpVNEP8H0aBhcU9EMj6rb/KCWvWfR3+pSmo4sUlpP136RtEFl+xGhnPyXfwBSasQCSGyYsUjZWb/aZU0H+hYFeGIX4yZB+GqpHHgQQhwOewjWWS9VuVw2yoohYlxnhYak9yqczi7IRd2MW+su8TUR6I1TO8iwE4iTWZ9vjL1q0HKCxPaQ+NDRkOS00g9KZRa6uMCM7xUoIQbojQiMeCWqN6mHP0IYxF/yYe6eg51KZaBJ7JuoFR1ExDgBEaFs5dw1EGT+a0oAast+KJne9cv2oiZyjndyXck4WDPclAw+javfHHZwQz53FEzTf4t4/XkTLQcffnHs27cJZuienFLvkuHkseuIItZagJdCvTUi7gdg72G1V+aY/Pd0Rctd6k5ocg2JOa3ABxqR/JzTWcET3efWdIJbFuMnXs+KD7aLbvdlxOpCiUIA0MSJL7+ej0tBIpP3eggjRpb05rCSSBk8SW8qZxi4iAgOPvbeb9oT6FPjiaIjpoxFxpEExRoF5qvh+n/EzcxHdXCWLt1WYA+NW6L7nB7ga+9HQgfhGdwsHM+ZVLsIgsR2/VxmDRiK3LwEbOlUeohPxEdy6OqnucrhnSvcVdddajQuhTdJMJXPG2JKWWYBZKA/soScPVNS3NdP2cs+sYlXVIfmll3asvNhWNMPOMus5FdVIc9XxomJqSGCdwH0PwBY2ZlYLvITrjtao/oLFZySfnz+eHL0WdQ6iF/ifkB+I2+imeLqSY7GUpYeUcfZV+M8k8C35ZyzWajJIErgfLyeBorjOCw/cVRixmXbZlL6yKVfrWY4xJJZHmKD1hh482PJOuE=,iv:RwZPncbiWmritaZCjPqe6wJ53PlXvF6/YClOfbEluJ8=,tag:oEe4L/L+v7MGDT7ELtumtg==,type:str]
sops:
  age:
    - recipient: age1vtnndcu4fmcthtam7zqlpt2nuqms7vhfdmljs08zzxkrnjy7344qt0td4v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhRmxNZVMyOWc5M0ZMZ2ow
        d1ZaMDVwNDRYbWJTa0lyQzkvZGg4SzQxbWlrClJuN3ZUcHlPZlNnNitTa1RuUVBi
        TWZkbVFCYnVoTGxnRUFxK3B3VkFyMzgKLS0tIDVkUlliUFVaYWp5VnpFZ3dzcDRx
        ZFROV0NKdHhheFcvWThOK1NCaWpCTjQKbdd+VVpamLDyPUqNv+CQ2aEU+4wq9XRY
        zVL8HuK3HntizznR30LYhoGC9dNjifsv1+59Cdbo9wD5kiYc14wWvA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-11T05:50:07Z"
  mac: ENC[AES256_GCM,data:SO+LYp0yO3rjAeCHQrsjIaQVem3aOKPaZF5XwDG1N3SVgr4JxiWRvu1PY7SD2LjS2SFAr+BWcNKtO8mb99U4pDXxZyN+SytP40rCPRfFiNBdgDCpyiySNXH4heLk5jhw7UitAi7BOo40+A/LbQifYsbSsCe/kAFddEPdy0dzJvw=,iv:HB/dG93v15JxRW45a270Xm6h3x+U5MM3muQ2pPpUqHc=,tag:44rENLd1lqtYi3WFMKZFMw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
