apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  namespace: monitoring
stringData:
  admin-user: ENC[AES256_GCM,data:X8to6q8=,iv:qJ1KYzBmfIgKY8cLTUcTMiXhClRmr/EAg7X1MUCcXHA=,tag:eZwNkN+htrWjaacPYaN7wQ==,type:str]
  admin-password: ENC[AES256_GCM,data:vMyrQ20IBTqFzg==,iv:p6uatSjcj/FYb0PhsvPJR54DLy29UIlWC3ZNRG7kFC4=,tag:nCpSUmDIqPv9tNWg32eckg==,type:str]
sops:
  age:
    - recipient: age1vtnndcu4fmcthtam7zqlpt2nuqms7vhfdmljs08zzxkrnjy7344qt0td4v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhRmxNZVMyOWc5M0ZMZ2ow
        d1ZaMDVwNDRYbWJTa0lyQzkvZGg4SzQxbWlrClJuN3ZUcHlPZlNnNitTa1RuUVBi
        TWZkbVFCYnVoTGxnRUFxK3B3VkFyMzgKLS0tIDVkUlliUFVaYWp5VnpFZ3dzcDRx
        ZFROV0NKdHhheFcvWThOK1NCaWpCTjQKbdd+VVpamLDyPUqNv+CQ2aEU+4wq9XRY
        zVL8HuK3HntizznR30LYhoGC9dNjifsv1+59Cdbo9wD5kiYc14wWvA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-10T15:49:10Z"
  mac: ENC[AES256_GCM,data:ujjnqhf/hLA5YIgX4AZuL0paK0U8Zm9JmZR3mFIr22JP1EBzb6C3ATYGpOIU/v/6CMynO8ojKUEBL7QWKYhvqPQUIA5loivN3KU6uZG5Nbvh1xLcQj198mDXJe6Q5Y7CB+wj+9QTBWBVzHlTFrqg0Iy6f57mrUTYdkQ8Tbcc54o=,iv:N1ynrz8fKBUSqQZwqIAxIqoo6PQQDQc34uXpx8H30dE=,tag:9W0TPiGJm8dYPWiK5QhSxg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: sing-box-tun-config
  namespace: monitoring
type: Opaque
stringData:
  config.json: ENC[AES256_GCM,data:5mSIdGTh6cmBjzlICfs7qDSQg0TXIROaWir7Jc/qCKwJvJeaQj8hA6vwBQKXh9I2xmdAAqEfY9BzcJTzD/OG7t8XKLMkIP7K0gG3fBRmdZkJK+cCrHU+2doLYl4OKsmSSwFxPyS/DzN0XuQGY4buobf16FMTD37KVjSsL2ik/P7vNxggtP1kGOKY+D0u0i7Elf5KEo8TXwh1tlRzGDRIcvs/+uFHG3pp7uvZ1ddOCDLYjTJ3OHh3nd+DdaGBBH37Yx1DQ4E9PeikGN7lJ5OgYqWLtzeeO6J0l0klydR/GpS7kqRn4zMO+6CEvbQb4HYfugD99IHZBf1HVd4k9iJa03cJaAt3FuR6VHVn77BOj92+S8qb91fUvUYZqLotyaWgqPHJUbWkP+HTwjJjCrdqijG2VsemVeaPFvZww+tFOth/wmUYprFySKNvPF7gWtvzGyCLQriTnJgR66Qcrks/gpxM/I1GAa2onttA6d6zJFUsdhp6MntKR0Y/h4GrkUNIhYwnbKNQqSGqCB0LYmYuK7byvx7OoUCGHwoMSH3bZDvOy0UrlyAux4Lf/9MHE7SR+XzwsZTg+KKmkG0sMtjDDkwxzHdsZQgZpK/cFMrGfYL349IbJdlfuZ0aJ8kBg0qaaoC9B8wl6w8b8A9oAfBq/sJGR6Fm45noGItulXqga99Bfxk10exxB5Kbnk542e3lqUDAa3zLvtJIHzPCcy2Me2Z8ndOSTndKSabH9XhJ/iMLb1dZXRlSzamKdt3UnVebIuIaiL2whaTTrGzVtlAqDg/V92f5LBHWUfkIrNC4uV95LSyyMK7iYhc2giaJnqs/9QsdAZQCxPkZO9rzfDbl6bUq1G595JFL4R07cXNAQ+IHhp3rVgaProjobt3z/NrmnT0jOQjZtVdymyTHbE0l4Up6N4eeHsIC/HqZ7xx1fL+rX1/cht0ianwzJfrBnmBfNvZwvMVt38ep53xqL5gIaGvABh9e0yn5Q8RW6lXe3130ypaoDItrs0bGMZwGAdSsZzyca9/2j2I/Yr9PVg/T1eZbcTrEvyuEopSJxUYMm//VkqOsuCoIz+aD6WcrgDfc+xPax0XFsuE0+xtOsz/ToxPwUpDRMDzKfe+u9LD+r7QQNpSZWb3O5aVM5KXq7N+Dk+yJL9CQVWaykEGWwv0251/cprIM70j7JH2g4DoPieAIPiuYC/JbqosfetWb/Xd0CiGB/w75wO5+M5+ZmGPxTR38TOPr5wKc3RW5ED7h4khIyPx5XcXWZiEXivp1YiQmuVQAoskyt4qKrYspmpgbaRPx5Pc20G+4ilaxgxWBH4+Y9UoPK6G76m7CI5eYmt6tC+zxtKUEyqQb9DcOgiE0b/xaQLBVHziRI6xLqGhWuw7WFcgVB1Za3Cc4u5XPh3sYHqCiV1ROEzGzftwWmPG4IRqD34aJTFBXGUt+M1eu4jjFX+U=,iv:XUYz4ernkiSmqNev+P0fJjaxOlSvIA3/2yYtWtNFA5k=,tag:bfRRg5jr4sSmR2HDc7sWJQ==,type:str]
sops:
  age:
    - recipient: age1vtnndcu4fmcthtam7zqlpt2nuqms7vhfdmljs08zzxkrnjy7344qt0td4v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhRmxNZVMyOWc5M0ZMZ2ow
        d1ZaMDVwNDRYbWJTa0lyQzkvZGg4SzQxbWlrClJuN3ZUcHlPZlNnNitTa1RuUVBi
        TWZkbVFCYnVoTGxnRUFxK3B3VkFyMzgKLS0tIDVkUlliUFVaYWp5VnpFZ3dzcDRx
        ZFROV0NKdHhheFcvWThOK1NCaWpCTjQKbdd+VVpamLDyPUqNv+CQ2aEU+4wq9XRY
        zVL8HuK3HntizznR30LYhoGC9dNjifsv1+59Cdbo9wD5kiYc14wWvA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-10T15:49:10Z"
  mac: ENC[AES256_GCM,data:ujjnqhf/hLA5YIgX4AZuL0paK0U8Zm9JmZR3mFIr22JP1EBzb6C3ATYGpOIU/v/6CMynO8ojKUEBL7QWKYhvqPQUIA5loivN3KU6uZG5Nbvh1xLcQj198mDXJe6Q5Y7CB+wj+9QTBWBVzHlTFrqg0Iy6f57mrUTYdkQ8Tbcc54o=,iv:N1ynrz8fKBUSqQZwqIAxIqoo6PQQDQc34uXpx8H30dE=,tag:9W0TPiGJm8dYPWiK5QhSxg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
