apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  namespace: monitoring
stringData:
  admin-user: ENC[AES256_GCM,data:X8to6q8=,iv:qJ1KYzBmfIgKY8cLTUcTMiXhClRmr/EAg7X1MUCcXHA=,tag:eZwNkN+htrWjaacPYaN7wQ==,type:str]
  admin-password: ENC[AES256_GCM,data:vMyrQ20IBTqFzg==,iv:p6uatSjcj/FYb0PhsvPJR54DLy29UIlWC3ZNRG7kFC4=,tag:nCpSUmDIqPv9tNWg32eckg==,type:str]
sops:
  age:
    - recipient: age1vtnndcu4fmcthtam7zqlpt2nuqms7vhfdmljs08zzxkrnjy7344qt0td4v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhRmxNZVMyOWc5M0ZMZ2ow
        d1ZaMDVwNDRYbWJTa0lyQzkvZGg4SzQxbWlrClJuN3ZUcHlPZlNnNitTa1RuUVBi
        TWZkbVFCYnVoTGxnRUFxK3B3VkFyMzgKLS0tIDVkUlliUFVaYWp5VnpFZ3dzcDRx
        ZFROV0NKdHhheFcvWThOK1NCaWpCTjQKbdd+VVpamLDyPUqNv+CQ2aEU+4wq9XRY
        zVL8HuK3HntizznR30LYhoGC9dNjifsv1+59Cdbo9wD5kiYc14wWvA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-13T14:46:39Z"
  mac: ENC[AES256_GCM,data:mYV6LABKncd5/NhT/XhYPfcoNiCkE4Hqisl/FQifK8B8lP/6vz35umyY5v3IGjfTqf1zj9Pfs8ce91YbjY4nRikkfstoJ7cP5QycVYlwa1HgjaTB2nwTbiAruTiKWP+97m/a0MjZEhTMAvA7nJJEa5s3zN1BQS+gNNE6XjtbnS8=,iv:UrDILf656ogc8SRksB2AYQwDgOGdt6ZAxG8fnYT8kYU=,tag:KtFzj4XEzQTn9CTh/LFyVA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: sing-box-tun-config
  namespace: monitoring
type: Opaque
stringData:
  config.json: ENC[AES256_GCM,data:Nt9Y/lANbJ2YSZcdTpns5YWoWu0VELGOuzNE+6TxVVzU9yoSFROTgNjRk+9fodziSTfJyZ+ZcYGMvMG166aSbYBpHEVXepiY78KGZ8qqfLLRDJPScMTe8DxeqAAv9jqlZroclKVq+QuNDTOEkuVVtOmwLEzjApH2ftkCCxqiOc1dBah0/xX3yvif9zUQt/AI45pFou2eryxMJGz8WaspYVKYZIFBhaHf2rrGuoPDv4D1DG7KTHCEoV0eWLqE7T6Vo4rrzr9qQPdF83CZof4UiT7KJH9KKdmooPCtpKA3zhvl6ibmaE+3oY5Jk9YtFcU7IA51oIyN8CxlT1Fz+zKPuXmJNWOZzhkuQpGcTObU0TVhk7sj3jJ0gDnmrgJTC6rZS8XnqoK/HIQrMZ/vDvrFtCqTO9iJfpmIg8Ga9GK+jQww39mPIuSptPLQuoYHDjFf8q8LuOQ4aEGVopm9wIcLkzokc+JKPEaafp6DFZaebr5dFVbvjXfI+nW1KGFmkPlMy9LZef+yp7yxAJFfxKi2++jp5W4+24/sO9iQ3/YPeiUmUmNNsFAX227vBHyPawB8j+rC2iPe4v9+LCRAcGmW42i9OK0WZ0r7w8T2svehqRBPXkxr7BoUzVbij4BrtpMrOrcpQiiMhft2mD+AeGhA1lKimW0QtfFqHYELfR6F7zQV/mbKI/DCd/Yrn/2FDu0+osQdfrNcKVJr/Uwa6Y3dfwGSLw8LGvu4nmzGay04zK7qtWim68FPrKloV5CDglUO26VtBotVAtbSZJI8mVwMn5k+IC8YGg65ZyRpTLUtaaKGas/7WACNPIZ56N5LdUMDr17wDjHi5LGRslIRScrIgrbtczFpX/okqWaCVDKaLQiOWrZ/1/Fr68aa8Bu5BMgRm7K8pf3iCPZQohvS315qP8bXZIARzOIFHBb/JtJrxR5LgknynEH+JZf+gOEwSWZyFlNgunu0CPBrZQdka7n1Z/VNiGL6QHbHX527wzYq+qfSKiAxkpn30qkDWOL0IhIjcv7E4744SbonMK8dX2WRqr5nKrJ7LpmpkAW2U1C7YBj5kep3i7jTZa+m1d2AvM++xAcwT8QIdOJiZxRUi+NEHyto+rguSuS2UpiZCqJneZzv7WAgoZpqyomWrpWAxcsgS2tmkj9d1/lOu7VMYaCYqp5fICVXqc8r5t2jMue/63IeoAhXHe4AQ6tDzeL1prfntlPok/OzADSG3fWGabUxcYI0MkrcdI0ta0gyIG8vyQin8xcQeXODN/KgdNzKhCkQrtupzGQyzQ3vROWswXllZBkJf3iQk2qRN6/2qycjCLQ6uT8i2IiASxF8pQvzBOp6P+4MpTER0/mK0L6cGb2XHG/w3KXcXC4ekQDrW9UNx/a6fsN3qBUKosoFic6JYnyaLaz7PgaaqwmFDaOQY9Sz8FAgRj8hIf5dgQzzxhWRIPMVhK5J66lB+kqBBuTMXtafLuLjqFCfOxGkF60J5orQZJDm1IsDzGXnQuigLLChbdXMCRZNdPpreUo9bK2eosBlDLPN9Sxwc9RRBfoGUzJTB1rZn1VDEDVhACBw315g+QuKcsJpooMkMDFzpC6R3J1etwE/UA==,iv:FsJ+7KtS9qvU06mkmd3zPVzeuMfKlUuX39GmFprMLqE=,tag:A9qpmgMbGvNFJUfRQrGRyg==,type:str]
sops:
  age:
    - recipient: age1vtnndcu4fmcthtam7zqlpt2nuqms7vhfdmljs08zzxkrnjy7344qt0td4v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhRmxNZVMyOWc5M0ZMZ2ow
        d1ZaMDVwNDRYbWJTa0lyQzkvZGg4SzQxbWlrClJuN3ZUcHlPZlNnNitTa1RuUVBi
        TWZkbVFCYnVoTGxnRUFxK3B3VkFyMzgKLS0tIDVkUlliUFVaYWp5VnpFZ3dzcDRx
        ZFROV0NKdHhheFcvWThOK1NCaWpCTjQKbdd+VVpamLDyPUqNv+CQ2aEU+4wq9XRY
        zVL8HuK3HntizznR30LYhoGC9dNjifsv1+59Cdbo9wD5kiYc14wWvA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-13T14:46:39Z"
  mac: ENC[AES256_GCM,data:mYV6LABKncd5/NhT/XhYPfcoNiCkE4Hqisl/FQifK8B8lP/6vz35umyY5v3IGjfTqf1zj9Pfs8ce91YbjY4nRikkfstoJ7cP5QycVYlwa1HgjaTB2nwTbiAruTiKWP+97m/a0MjZEhTMAvA7nJJEa5s3zN1BQS+gNNE6XjtbnS8=,iv:UrDILf656ogc8SRksB2AYQwDgOGdt6ZAxG8fnYT8kYU=,tag:KtFzj4XEzQTn9CTh/LFyVA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
