---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg-system
  namespace: cnpg-system
spec:
  interval: 30m
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.27.0       
      sourceRef:
        kind: HelmRepository
        name: cnpg-system
        namespace: flux-system
  install:
    createNamespace: true
    timeout: 10m
  upgrade:
    remediation:
      retries: 3
  values:
    monitoring:
      podMonitorEnabled: false

