---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: wallabag
  namespace: flux-system
spec:
  dependsOn:
    - name: infra
  interval: 10m
  path: "./k8s/wallabag"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m
  decryption:
    provider: sops
    secretRef:
      name: sops-age

---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: wallabag
  namespace: flux-system
spec:
  image: docker.io/wallabag/wallabag
  interval: 12h

---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: wallabag
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: wallabag
  policy:
    semver:
      range: "*"

---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: wallabag-update
  namespace: flux-system
spec:
  interval: 1h
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '{{range .Changed.Changes}}{{print .OldValue}} -> {{println .NewValue}}{{end}}'
    push:
      branch: flux-wallabag-update
  update:
    path: ./k8s/wallabag
    strategy: Setters
