apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: envoy-gateway
  namespace: flux-system
spec:
  interval: 5m
  url: oci://docker.io/envoyproxy/gateway-helm
  ref:
    tag: "v1.7.0" # {"$imagepolicy": "flux-system:envoy-gateway:tag"}

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway-system
  namespace: envoy-gateway-system
spec:
  interval: 30m
  timeout: 30m
  chartRef:
    kind: OCIRepository
    name: envoy-gateway
    namespace: flux-system
  targetNamespace: envoy-gateway-system
  createNamespace: true
  values:
    deployment:
      resources:
        limits:
          memory: 1024Mi
        requests:
          cpu: 100m
          memory: 256Mi
    service:
      type: LoadBalancer
      annotations:
        metallb.io/ip-allocated-from-pool: first-pool
    config:
      envoyGateway:
        provider: Kubernetes
