name: e2e

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  kubernetes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Flux
        uses: fluxcd/flux2/action@main

      - name: Setup Kubernetes
        uses: helm/kind-action@v1.14.0
        with:
          cluster_name: e2e

      - name: Install Flux in Kubernetes kind
        run: flux install --components-extra=image-reflector-controller,image-automation-controller

      - name: Setup cluster infra reconcilation
        run: |
          printf '%s' "$SOPS_AGEKEY" | kubectl create secret generic sops-age \
            --namespace=flux-system \
            --from-file=sops.agekey=/dev/stdin

          flux create source git flux-system \
          --url=${{ github.event.repository.html_url }} \
          --commit=${{ github.event.pull_request.head.sha }} \
          --ignore-paths="clusters/flux-system/"

          flux create kustomization infra \
          --source=flux-system \
          --path=./clusters/infra \
          --prune=true \
          --wait=false

        env:
          SOPS_AGEKEY: ${{ secrets.SOPS_AGEKEY }}


      - name: Verify cluster reconciliation
        run: |
          kubectl -n flux-system wait kustomization/infra --for=condition=ready --timeout=10m

      - name: Detect changed app
        id: app
        run: |
          changed_files=$(git diff --name-only \
            "${{ github.event.pull_request.base.sha }}" \
            "${{ github.event.pull_request.head.sha }}")

            echo "Changed files:"
            echo "$changed_files"

            apps=$(echo "$changed_files" | \
              awk -F/ '$1 == "k8s" && NF >= 2 {print $2}' | \
              sort -u)

            if [[ -z "$apps" ]]; then
              echo "No application changes detected"
              exit 1
            fi

            if [[ $(echo "$apps" | wc -l) -ne 1 ]]; then
              echo "More than one application changed:"
              echo "$apps"
              exit 1
            fi

          app=$(echo "$apps")

          echo "Application: $app"
          echo "app=$app" >> "$GITHUB_OUTPUT"

      - name: Reconcile changed app
        run: |
          flux create kustomization "$APP" \
            --source=flux-system \
            --path="./k8s/$APP" \
            --prune=true \
            --wait=false
        env:
          APP: ${{ steps.app.outputs.app }}

      - name: Verify app reconcilation
        run: |
          kubectl -n flux-system wait \
            kustomization/${{ steps.app.outputs.app }} \
            --for=condition=ready \
            --timeout=10m

      - name: Debug failure
        if: failure()
        run: |
          kubectl -n flux-system get all
          kubectl -n flux-system logs deploy/source-controller
          kubectl -n flux-system logs deploy/kustomize-controller
          kubectl -n flux-system logs deploy/helm-controller
          flux get all --all-namespaces

